apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-fresh-app-deployment
  namespace: my-fresh-app # Define your app's namespace
  labels:
    app: my-fresh-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-fresh-app
  template:
    metadata:
      labels:
        app: my-fresh-app
    spec:
      # This secret allows Kubernetes to pull from private ECR
      imagePullSecrets:
        - name: ecr-cred-secret # This must match the secret name created later
      containers:
        - name: my-fresh-app-container
          image: /my-fresh-app:dc9e03fe4316ba719a851b699c3eabc6298eef18
          ports:
            - containerPort: 80 # Nginx serves on port 80
          resources:
            requests: # Request minimal resources to ensure scheduling
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
