apiVersion: v1
kind: Service
metadata:
  name: my-fresh-app-service
  namespace: my-fresh-app
spec:
  selector:
    app: my-fresh-app
  type: NodePort # This exposes the service on your k0s node's IP and a high port
  ports:
    - protocol: TCP
      port: 80 # Service port inside the cluster
      targetPort: 80 # Container port
      # nodePort: 30080 # Optional: You can specify a fixed NodePort between 30000-32767
